<GUILayout>
    size: 600, 400

    FloatLayout:
        orientation: "vertical"

        allow_stretch: True


        Label:
            text: "Recipients' Emails:"
            height: 30
            pos_hint: {"left": 0.1}
            pos_hint: {"top": 0.1}


        TextInput:
            multiline: True
            height: 200
            pos_hint: {"left": 0.1}
            pos_hint: {"top": 0.4}


